name: Build & Release PascheK Chatbox

on:
  push:
    tags:
      - "v*" # ex: v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠 Build application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paschek-chatbox-${{ matrix.os }}
          path: dist/

  release:
    name: 🚀 Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-builds

      - name: 🧩 Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-builds/**/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}